third/webservice/WithPet/urls.py
#from . import views


#urlpatterns = [
    #path('', views.index, name='index'),

#]



from .views import *

from django.contrib import admin
from django.urls import path, include
# index는 대문, blog는 게시판
from WithPet.views import index, blog, posting, spot



# 이미지를 업로드하자
from django.conf import settings
from django.conf.urls.static import static

urlpatterns=[
    #path('',index),
    #path('blog/',blog),

    path('admin/', admin.site.urls),
    # 웹사이트의 첫화면은 index 페이지이다 + URL이름은 index이다
    path('', index, name='index'),
    # URL:80/blog에 접속하면 blog 페이지 + URL이름은 blog이다
    path('blog/', blog, name='blog'),
    # URL:80/blog/숫자로 접속하면 게시글-세부페이지(posting)
    path('blog/<int:pk>',posting, name="posting"),
    path('blog/new_post/', new_post),
    ##삭제 버튼
    path('blog/<int:pk>/remove/', remove_post),

    path('spot/', spot, name='spot'),
    path('spot-detail', spot_detail, name='spot-detail'),
    path('mypage/', my_page, name='mypage'),
] 

# 이미지 URL 설정
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

third/webservice/users/urls.py
from django.urls import path
from .views import * # user>views에서 모든 함수를 가져온다.
from django.contrib.auth import views as auth_views

app_name = "users"
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
  # django.contrib.auth앱의 LoginView 클래스를 활용했으므로 별도의 views.py 파일 수정이 필요 없음
]

third/webservice/webservice/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

#로그인기능
from accounts import views as accounts_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('WithPet.urls')),
    path('users/', include('users.urls')), #users>urls.py에서 관리할 거야
    path('login/', accounts_views.login,name='login'),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

third/webservice/WithPet/models.py
from django.db import models

# Create your models here.


# 게시글(Post)엔 제목(postname), 내용(contents)이 존재합니다
class Post(models.Model):
    postname = models.CharField(max_length=50)
     # 게시글 Post에 이미지 추가
    mainphoto = models.ImageField(upload_to='images/', blank=True, null=True)
    contents = models.TextField()


     # 게시글의 제목(postname)이 Post object 대신하기
    def __str__(self):
        return self.postname


class Photo(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, null=True)
    image = models.ImageField(upload_to='images/', blank=True, null=True)

third/webservice/accounts/models.py
from django.db import models

# Create your models here.

third/webservice/users/models.py
from django.db import models

# Create your models here.

third/webservice/WithPet/views.py
from django.shortcuts import render, redirect

# View에 Model(Post 게시글) 가져오기
from .models import Post, Photo


# Create your views here.

# index.html 페이지를 부르는 index 함수
def index(request):
    return render(request,'main/index.html')


# blog.html 페이지를 부르는 blog 함수
def blog(request):
     # 모든 Post를 가져와 postlist에 저장
    postlist = Post.objects.all()
    # blog.html 페이지를 열 때, 모든 Post인 postlist도 같이 가져옴
    return render(request, 'main/blog.html', {'postlist':postlist})


# blog의 게시글(posting)을 부르는 posting 함수
def posting(request, pk):
    # 게시글(Post) 중 pk(primary_key)를 이용해 하나의 게시글(post)를 검색
    post = Post.objects.get(pk=pk)
    # posting.html 페이지를 열 때, 찾아낸 게시글(post)을 post라는 이름으로 가져옴
    return render(request, 'main/posting.html', {'post':post})


# spot.html
def spot(request):
    return render(request, 'main/spot.html')

def spot_detail(request):
    return render(request, 'main/spot_detail.html')

def my_page(request):
    return render(request, 'main/mypage.html')

#글쓰기

def new_post(request):
    if request.method == 'POST':
        if request.POST['mainphoto']:
            new_article=Post.objects.create(
                postname=request.POST['postname'],
                contents=request.POST['contents'],
                mainphoto=request.POST['mainphoto'],
            )
        else:
            new_article=Post.objects.create(
                postname=request.POST['postname'],
                contents=request.POST['contents'],
                mainphoto=request.POST['mainphoto'],
            )
        return redirect('/blog/')
    return render(request, 'main/new_post.html')



#삭제기능

def remove_post(request, pk):
    post = Post.objects.get(pk=pk)
    if request.method == 'POST':
        post.delete()
        return redirect('/blog/')
    return render(request, 'main/remove_post.html', {'Post': post})

third/webservice/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib import auth
from django.contrib.auth.models import User

# Create your views here.
def login(request):
    #POST 요청이 들어오면 로그인 처리를 해줌
    if request.method == 'POST':

        userid = request.POST['username']
        pwd = request.POST['password']
        user = auth.authenticate(request, username=userid, password=pwd)
        if user is not None:
            auth.login(request, user)
            return redirect('blog')
        else:
            return render(request, 'login.html')

    #GET 요청이 들어오면 ligin form을 담고 있는 login.html을 띄어줌
    else:
        return render(request, 'login.html')

third/webservice/users/views.py
from django.shortcuts import render

# Create your views here.

third/webservice/WithPet/templates/main/blog.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
  <head>
    <title>위드펫</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="{% static 'css/style.css' %}?after" rel="stylesheet" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <div class="course-wrapper">
      <div id="header" class="navbar">
        <a href="/" id="hd-main-logo" class="clear-a"
          ><img src="{% static 'img/logo.png' %}"
        /></a>
        <form class="d-flex" role="search">
          <input
            class="search-bar me-2"
            type="search"
            placeholder="검색어를 입력해주세요."
            aria-label="Search"
          />
          <button type="submit" id="ic-search" class="clear-btn">
            <img src="{% static 'img/search.png' %}" alt="검색" />
          </button>
        </form>
        {% if user.is_authenticated %}
          <div id="hd-login">
            <a href="{% url 'users:logout' %}" class="clear-a">로그아웃</a>
          </div>
          <div id="hd-signup">
            <a href="/mypage" class="clear-a">마이페이지</a>
          </div>
        {% else %}
        <div id="hd-login">
          <a href="{% url 'login' %}" class="clear-a">로그인</a>
        </div>
        <div id="hd-signup">
          <a href="./signup.html" class="clear-a">회원가입</a>
        </div>
        {% endif %}

      </div>
      <div id="course-condition-container">
        <div class="flex-left">
          <p class="sep-text">지역</p>
          <input type="text" class="course-region" placeholder="제주도" />
          <p class="sep-text">기간</p>
          <input type="text" class="course-region" placeholder="당일치기" />
        </div>
        <div class="flex-right">
          <a href="/blog" class="clear-a" id="selected-course">코스</a>
          <p class="slash-line">|</p>
          <a href="/spot" class="clear-a" id="selected-spot">스팟</a>
        </div>
      </div>
      <div class="sep-line"></div>

      <div class="post">
        <img src="{% static 'img/post.png'%}" alt="나의 여행 코스 소개하기" />
        <a href="new_post/" class="clear-a">
          <p id="post-text">나의 여행 코스 소개하기</p>
        </a>
      </div>

      <!-- 코스 게시물 받아와서 보여주기 -->
      <div class="course-box-container">
        {% for list in postlist %}
        <div class="course-container">
          <a href="{{list.pk}}"
            ><img src="{% static 'img/post-thumnail.png' %}" alt=""
          /></a>
          <div class="post-desc">
            <div class="flex-left">{{list.postname}}</div>
            <div class="flex-right count">
              <img
                src="{% static 'img/comment.png' %}"
                alt="댓글"
                width="20"
                height="20"
              />
              <p class="count-text">4</p>
              <img
                src="{% static 'img/heart.png' %}"
                alt="좋아요"
                width="20"
                height="20"
              />
              <p class="count-text">3</p>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
      {% comment %}
      <nav aria-label="Page navigation example" class="pagination-pos">
        <ul class="pagination">
          <li class="page-item">
            <a class="page-link" href="#" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
            </a>
          </li>
          <li class="page-item"><a class="page-link" href="#">1</a></li>
          <li class="page-item"><a class="page-link" href="#">2</a></li>
          <li class="page-item"><a class="page-link" href="#">3</a></li>
          <li class="page-item">
            <a class="page-link" href="#" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
            </a>
          </li>
        </ul>
      </nav>
      {% endcomment %}
    </div>
    <footer>위드펫 WithPet | LikeLion 10th SWU Team5</footer>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
      crossorigin="anonymous"
    ></script>
    <script src="{% static 'js/top-nav.js' %}"></script>
  </body>
</html>

third/webservice/WithPet/templates/main/index.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
  <head>
    <title>위드펫</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx"
      crossorigin="anonymous"
    />
    <link href="{% static 'css/style.css' %}?after" rel="stylesheet" />
  </head>
  <body>
    <div class="index-wrapper">
      <div id="header" class="navbar">
        <a href="/" id="hd-main-logo" class="clear-a"
          ><img src="{% static 'img/logo.png' %}"
        /></a>
        <form class="d-flex" role="search">
          <input
            class="search-bar me-2"
            type="search"
            placeholder="검색어를 입력해주세요."
            aria-label="Search"
          />
          <button type="submit" id="ic-search" class="clear-btn">
            <img src="{% static 'img/search.png'%}" alt="검색" />
          </button>
        </form>
        {% if user.is_authenticated %}
          <div id="hd-login">
            <a href="{% url 'users:logout' %}" class="clear-a">로그아웃</a>
          </div>
          <div id="hd-signup">
            <a href="/mypage" class="clear-a">마이페이지</a>
          </div>
        {% else %}
        <div id="hd-login">
          <a href="{% url 'login' %}" class="clear-a">로그인</a>
        </div>
        <div id="hd-signup">
          <a href="./signup.html" class="clear-a">회원가입</a>
        </div>
        {% endif %}
      </div>
      <div id="where-to-go">OO이와 함께 <br />어디로 떠나고 싶으신가요?</div>
      <div id="box">
        <div id="ic-map">
          <img
            src="{% static 'img/map.png'%}"
            alt="지도"
            width="30"
            height="30"
          />
        </div>
        <form id="search-bar" role="search">
          <input
            class="form-control me-2"
            type="search"
            placeholder="가고싶은 지역을 입력하세요."
            aria-label="Search"
          />
        </form>
        <div class="line"></div>
        <button type="button" id="btn-course" onClick="location.href='/blog/'">
          다른 사람들의 반려동물 동반 여행 코스 둘러보기
        </button>
        <button type="button" id="btn-spot" onClick="location.href='/spot'">
          반려동물 동반 가능 스팟 찾기
        </button>
      </div>
      <div id="service-desc">
        <div
          id="carouselExampleIndicators"
          class="carousel slide"
          data-bs-ride="carousel"
        >
          <div class="carousel-indicators">
            <button
              type="button"
              data-bs-target="#carouselExampleIndicators"
              data-bs-slide-to="0"
              class="active"
              aria-current="true"
              aria-label="Slide 1"
            ></button>
            <button
              type="button"
              data-bs-target="#carouselExampleIndicators"
              data-bs-slide-to="1"
              aria-label="Slide 2"
            ></button>
            <button
              type="button"
              data-bs-target="#carouselExampleIndicators"
              data-bs-slide-to="2"
              aria-label="Slide 3"
            ></button>
            <button
              type="button"
              data-bs-target="#carouselExampleIndicators"
              data-bs-slide-to="3"
              aria-label="Slide 4"
            ></button>
          </div>
          <div class="carousel-inner">
            <div class="carousel-item active">
              <img
                src="{% static 'img/carousel_03.jpeg' %}"
                class="d-block w-100"
                alt="..."
                width="auto"
                height="573"
              />
              <div class="carousel-caption d-none d-md-block">
                <h5>사랑하는 나의 반려동물과 함께 떠나보세요!</h5>
                <p>
                  반려동물 동반 가능한 장소와 제공하는 서비스를 한눈에 확인할 수
                  있어요.
                </p>
              </div>
            </div>
            <div class="carousel-item">
              <img
                src="{% static 'img/carousel_02.jpeg' %}"
                class="d-block w-100"
                alt="..."
                width="auto"
                height="573"
              />
              <div class="carousel-caption d-none d-md-block">
                <h5>같이 여행하고 싶은데, 좋은 곳 없을까?</h5>
                <p>다른 사람들의 반려동물 동반 여행 코스를 볼 수 있어요.</p>
              </div>
            </div>
            <div class="carousel-item">
              <img
                src="{% static 'img/carousel_01.jpg' %}"
                class="d-block w-100"
                alt="..."
                width="auto"
                height="573"
              />
              <div class="carousel-caption d-none d-md-block">
                <h5>함께해서 행복한 순간들</h5>
                <p>사소했던 일상이 더욱 특별해질 거예요.</p>
              </div>
            </div>
            <div class="carousel-item">
              <img
                src="{% static 'img/carousel_04.jpg' %}"
                class="d-block w-100"
                alt="..."
                width="auto"
                height="573"
              />
              <div class="carousel-caption d-none d-md-block">
                <h5>메리와 소중했던 2박 3일</h5>
                <p>마음 편하게 함께 여행하세요.</p>
              </div>
            </div>
          </div>
          <button
            class="carousel-control-prev"
            type="button"
            data-bs-target="#carouselExampleIndicators"
            data-bs-slide="prev"
          >
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button
            class="carousel-control-next"
            type="button"
            data-bs-target="#carouselExampleIndicators"
            data-bs-slide="next"
          >
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
      </div>
    </div>
    <footer>위드펫 WithPet | LikeLion 10th SWU Team5</footer>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

third/webservice/WithPet/templates/main/new_post.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
  <head>
    <title>위드펫</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="{% static 'css/style.css'%}?after " rel="stylesheet" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <div class="new_post-wrapper">
      <div id="header" class="navbar">
        <a href="/" id="hd-main-logo" class="clear-a"
          ><img src="{% static 'img/logo.png' %}"
        /></a>
        <form class="d-flex" role="search">
          <input
            class="search-bar me-2"
            type="search"
            placeholder="검색어를 입력해주세요."
            aria-label="Search"
          />
          <button type="submit" id="ic-search" class="clear-btn">
            <img src="{% static 'img/search.png' %}" alt="검색" />
          </button>
        </form>
        <div id="hd-login">
          <a href="{% url 'users:logout' %}" class="clear-a">로그아웃</a>
        </div>
        <div id="hd-signup">
          <a href="/mypage" class="clear-a">마이페이지</a>
        </div>
      </div>
      <div class="post-w-desc">OO님만의 여행 코스를 소개해주세요!</div>
      <form method="POST">
        {% csrf_token %}
        <div id="post-condition-container">
          <div class="flex-left">
            <p class="sep-text">제목</p>
            <input
              type="text"
              class="post-title-input"
              placeholder=""
              name="postname"
            />
            <p class="sep-text">지역</p>
            <input type="text" class="course-region" />
            <p class="sep-text">기간</p>
            <input type="text" class="course-region" />
          </div>
        </div>
        <div class="sep-line-post"></div>
        <div class="post-w-container">
          <textarea
            id="post-content"
            cols="30"
            rows="25"
            class="post-content-input"
            name="contents"
          ></textarea>
          <input type="file" name="mainphoto" class="post-main-photo" />
          <div>
            <button type="submit" class="btn-post" value="글쓰기">등록</button>
          </div>
        </div>
      </form>
    </div>

    {% for photo in post.photo_set.all %}
    <img src="{{ photo.image.url }}" width="50" /><br />
    {% endfor %}
    <footer>위드펫 WithPet | LikeLion 10th SWU Team5</footer>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

third/webservice/WithPet/templates/main/posting.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
  <head>
    <title>위드펫</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="{% static 'css/style.css'%}?after" rel="stylesheet" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <div class="posting-wrapper">
      <div id="header" class="navbar">
        <a href="/" id="hd-main-logo" class="clear-a"
          ><img src="{% static 'img/logo.png' %}"
        /></a>
        <form class="d-flex" role="search">
          <input
            class="search-bar me-2"
            type="search"
            placeholder="검색어를 입력해주세요."
            aria-label="Search"
          />
          <button type="submit" id="ic-search" class="clear-btn">
            <img src="{% static 'img/search.png' %}" alt="검색" />
          </button>
        </form>
        <div id="hd-login">
          <a href="{% url 'users:logout' %}" class="clear-a">로그아웃</a>
        </div>
        <div id="hd-signup">
          <a href="/mypage" class="clear-a">마이페이지</a>
        </div>
      </div>
      <div class="post-title">
        <div class="flex-left">
          {{post.postname}}
          <div class="post-author">by 몽몽</div>
        </div>
        <div class="edit-btn-container">
          <button type="button" class="btn-post-edit">수정</button>
          <button
            type="button"
            class="btn-post-edit"
            onClick="location.href='/blog/{{post.pk}}/remove'"
          >
            삭제
          </button>
        </div>
      </div>
      <div id="post-condition-container">
        <div class="flex-left">
          <p class="sep-text">지역</p>
          <input type="text" class="course-region" placeholder="제주도" />
          <p class="sep-text">기간</p>
          <input type="text" class="course-region" placeholder="당일치기" />
        </div>
        <div class="flex-right post-time">2022-08-07</div>
      </div>
      <div class="sep-line-post"></div>
      <div class="post-container">
        {% comment %} 사진 안 뜸 {% endcomment %}
        <!-- 이미지 보여주기 -->
        {% if post.mainphoto %}
        <img src="{{ post.mainphoto.url }}" alt="" height="600" />
        {% endif%}

        <div class="post-content">{{post.contents}}</div>
        <!-- 좋아요, 공유 버튼 -->
        <div class="share d-flex">
          <button type="button" class="img-btn">
            <img
              src="{% static 'img/heart.png' %}"
              alt=""
              width="20"
              height="20"
              class="post-ic"
            />
          </button>
          <div id="heart-count" class="post-cnt">1</div>
          <button type="button" class="img-btn">
            <img
              src="{% static 'img/share.png' %}"
              alt=""
              width="20"
              height="20"
              class="post-ic"
            />
          </button>
          <div id="share-count" class="post-cnt">2</div>
        </div>
        <div class="comment-container">
          <h5>댓글</h5>
          <div class="comment-w">
            <input
              type="text"
              placeholder="댓글을 입력해주세요."
              class="comment-input"
            />
            <button type="button" class="comment-up">등록</button>
          </div>
          <div class="comments">
            <div class="comment-info">
              <img
                src="{% static 'img/profile-img.png'%}"
                alt=""
                width="33"
                height="33"
              />
              <div class="comment-nick">
                몽몽
                <p class="comment-time">2022.08.08 13:15</p>
              </div>
            </div>
            <div class="comment-content">
              우리 몽이가 너무 즐겁게 뛰어놀아서 데려가길 잘 했다고 생각했어요!
              :) 다음에도 또 데려가려고요 (댓글1)
            </div>
            <button type="button" class="comment-re-btn">답글 작성</button>
          </div>
          <div class="comment-sep-line"></div>
          <div class="comments">
            <div class="comment-info">
              <img
                src="{% static 'img/profile-img.png'%}"
                alt=""
                width="33"
                height="33"
              />
              <div class="comment-nick">
                몽몽
                <p class="comment-time">2022.08.08 13:15</p>
              </div>
            </div>
            <div class="comment-content">
              우리 몽이가 너무 즐겁게 뛰어놀아서 데려가길 잘 했다고 생각했어요!
              :) 다음에도 또 데려가려고요 (댓글1)
            </div>
            <button type="button" class="comment-re-btn">답글 작성</button>
          </div>
          <div class="comment-sep-line"></div>
          <div class="comments">
            <div class="comment-info">
              <img
                src="{% static 'img/profile-img.png'%}"
                alt=""
                width="33"
                height="33"
              />
              <div class="comment-nick">
                몽몽
                <p class="comment-time">2022.08.08 13:15</p>
              </div>
            </div>
            <div class="comment-content">
              우리 몽이가 너무 즐겁게 뛰어놀아서 데려가길 잘 했다고 생각했어요!
              :) 다음에도 또 데려가려고요 (댓글1)
            </div>
            <button type="button" class="comment-re-btn">답글 작성</button>
          </div>
        </div>
      </div>
    </div>
    <footer>위드펫 WithPet | LikeLion 10th SWU Team5</footer>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

third/webservice/WithPet/templates/main/remove_post.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>글 삭제</title>
  </head>
  <body>
    <form method="POST">
      {% csrf_token %}
      <h3>{{ Post.postname }} - 삭제하기</h3>
      <button>삭제</button>
    </form>
  </body>
</html>

third/webservice/accounts/templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
  <head>
    <title>위드펫</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="{% static 'css/style.css' %}?after" rel="stylesheet" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <div class="login-wrapper">
        <div id="header" class="navbar">
            <a href="/" id="hd-main-logo" class="clear-a"
            ><img src="{% static 'img/logo.png' %}"
            /></a>
            <form class="d-flex" role="search">
            <input
                class="search-bar me-2"
                type="search"
                placeholder="검색어를 입력해주세요."
                aria-label="Search"
            />
            <button type="submit" id="ic-search" class="clear-btn">
                <img src="{% static 'img/search.png'%}" alt="검색" />
            </button>
            </form>
            <div id="hd-login">
            <a href="{% url 'login' %}" class="clear-a">로그인</a>
            </div>
            <div id="hd-signup">
            <a href="./signup.html" class="clear-a">회원가입</a>
            </div>
        </div>
        <form action="{% url 'login' %}" method = "POST">
            {% csrf_token %}
            <div id="login-container">
            <input type="text" class="input-text" name = 'username' placeholder="아이디(이메일)" />
            <input type="password" class="input-text" name = 'password' placeholder="비밀번호" />
            <div class="form-check login-check">
                <input
                class="form-check-input"
                type="checkbox"
                value=""
                id="flexCheckDefault"
                />
                <label class="form-check-label" for="flexCheckDefault">
                로그인 상태 유지
                </label>
            </div>
            <button type="submit" class="btn-login" value="로그인">로그인</button>
            </div>
        </form>
        <div id="find-id"><a href="#" class="clear-a">아이디 찾기</a></div>
        <div id="find-pw"><a href="#" class="clear-a">비밀번호 찾기</a></div>
    </div>
    <footer>위드펫 WithPet | LikeLion 10th SWU Team5</footer>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

third/webservice/users/templates/users/forms_errors.html
<!-- users>form_errors.html -->

{% if form.errors %}
{% for field in form %}
{% for error in field.errors %}
<!-- 필드 오류를 출력한다. -->
<div>
  <strong>{{ field.label }}</strong>
  {{ error }}
</div>
{% endfor %}
{% endfor %}
{% for error in form.non_field_errors %}
<!-- 넌필드 오류를 출력한다. -->
<div>
  <strong>{{ error }}</strong>
</div>
{% endfor %}
{% endif %}

third/webservice/users/templates/users/login.html
<!-- users>login.html -->

{% extends 'spot.html' %}
{% block content %}

<h1>로그인</h1>
<form method="post" action="{% url 'users:login' %}">
  {% csrf_token %}
  {% include 'users/form_errors.html' %}
  <div>
    <label>사용자 ID</label>
    <input type="text" name="username" id="username">
  </div>
  <div>
    <label>비밀번호</label>
    <input type="text" name="password" id="password">
  </div>
  <button type="submit">로그인</button>
</form>

{% endblock %}